// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/products/followed/{userId}/list": {
            "get": {
                "description": "Retorna produtos publicados nos últimos 14 dias pelos usuários seguidos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Lista produtos dos usuários seguidos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "date_asc",
                            "date_desc"
                        ],
                        "type": "string",
                        "description": "Ordenação",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.FollowedPostsResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetro inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products/promo-pub": {
            "post": {
                "description": "Publica um produto com promoção",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Publica um produto em promoção",
                "parameters": [
                    {
                        "description": "Dados do produto em promoção",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.PublishPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PublishResponse"
                        }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products/promo-pub/count": {
            "get": {
                "description": "Retorna a quantidade de produtos em promoção de um usuário",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Conta produtos em promoção",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PromoCountResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetro inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products/promo-pub/list": {
            "get": {
                "description": "Retorna a lista de produtos em promoção de um usuário",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Lista produtos em promoção",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PromoListResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetro inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products/publish": {
            "post": {
                "description": "Publica um produto sem promoção (HasPromo=false e Discount=0)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Publica um novo produto",
                "parameters": [
                    {
                        "description": "Dados do produto",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.PublishPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PublishResponse"
                        }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/follow/{userIdToFollow}": {
            "post": {
                "description": "Um usuário (userId) passa a seguir outro usuário (userIdToFollow)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Seguir um usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário que vai seguir",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID do usuário a ser seguido",
                        "name": "userIdToFollow",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Parâmetros inválidos ou regra de negócio",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/followed/list": {
            "get": {
                "description": "Retorna a lista de usuários que um userId segue. Pode ordenar por nome.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Listar seguidos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Ordenação por nome",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.FollowedListResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetro inválido, order inválida ou usuário não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/followers/count": {
            "get": {
                "description": "Retorna a quantidade de seguidores de um usuário (seller)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Contar seguidores",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário (seller)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.FollowersCountResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetro inválido ou usuário não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/followers/list": {
            "get": {
                "description": "Retorna a lista de seguidores de um usuário. Pode ordenar por nome.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Listar seguidores",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário (seller)",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "Ordenação por nome",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.FollowersListResponse"
                        }
                    },
                    "400": {
                        "description": "Parâmetro inválido, order inválida ou usuário não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{userId}/unfollow/{userIdToUnfollow}": {
            "post": {
                "description": "Um usuário (userId) deixa de seguir outro usuário (userIdToUnfollow)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Deixar de seguir um usuário",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do usuário que vai deixar de seguir",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID do usuário a deixar de seguir",
                        "name": "userIdToUnfollow",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Parâmetros inválidos ou regra de negócio",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Product": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "product_name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "http.FollowedListResponse": {
            "type": "object",
            "properties": {
                "followed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.SimpleUser"
                    }
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "http.FollowedPostsResponse": {
            "type": "object",
            "properties": {
                "posts": {},
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "http.FollowersCountResponse": {
            "type": "object",
            "properties": {
                "followersCount": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "http.FollowersListResponse": {
            "type": "object",
            "properties": {
                "followers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.SimpleUser"
                    }
                },
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "http.PromoCountResponse": {
            "type": "object",
            "properties": {
                "promo_products_count": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "http.PromoListResponse": {
            "type": "object",
            "properties": {
                "posts": {},
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "http.PublishResponse": {
            "type": "object",
            "properties": {
                "post_id": {
                    "type": "integer"
                }
            }
        },
        "http.SimpleUser": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "service.PublishPayload": {
            "description": "Payload para publicar um produto ou produto em promoção",
            "type": "object",
            "required": [
                "category",
                "date",
                "price",
                "product",
                "user_id"
            ],
            "properties": {
                "category": {
                    "type": "integer",
                    "example": 1
                },
                "date": {
                    "description": "Formato: dd-MM-yyyy",
                    "type": "string",
                    "example": "15-01-2024"
                },
                "discount": {
                    "type": "number",
                    "example": 0
                },
                "has_promo": {
                    "type": "boolean",
                    "example": false
                },
                "price": {
                    "type": "number",
                    "example": 100.5
                },
                "product": {
                    "$ref": "#/definitions/domain.Product"
                },
                "user_id": {
                    "type": "integer",
                    "example": 234
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "SocialMeli API",
	Description:      "API REST para gerenciamento de rede social de vendas (SocialMeli)\nImplementação completa do desafio SocialMeli em Go, usando Gin + storage em memória.\n\nFuncionalidades:\n- Gerenciamento de relacionamentos entre usuários (seguir/deixar de seguir)\n- Publicação de produtos e produtos em promoção\n- Listagem de posts de vendedores seguidos\n- Contagem e listagem de produtos em promoção",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
